### ISSUE TITLE
Failed to report cypress/e2e/smoke/actions.cy.js to Sauce Labs: Maximum number of redirects exceeded

### ISSUE THREAD

**Issue by EmreCihanbeyoglu** [saucelabs/sauce-cypress-plugin#41]
Hi,

Although it is working fine locally, when I run tests on Gitlab it gives me such an error: 

Failed to report cypress/e2e/smoke/actions.cy.js to Sauce Labs: Maximum number of redirects exceeded

In the beginning, I though that sauce credentials were not properly set. But when I print them, I am able to see them properly in the logs.  I am wondering if it might be because of proxy custom proxy configruation.

**Comment by alexplischke** [comment]
That does sound very much like a proxy interference 💯 We don't send any redirects on those specific endpoints.

**Comment by EmreCihanbeyoglu** [comment]
Thanks for your answer @alexplischke . when I use another runner which does not have any proxy configuration, it worked fine.
