### ISSUE TITLE
Update plugin example to es6 module syntax

### ISSUE THREAD

**Issue by anselmbradford** [saucelabs/sauce-cypress-plugin#64]
The default config generated by Cypress these days is an es6 module, whereas the config shown in this project's readme is commonjs. The example should be updated to the latest Cypress config format.

**Comment by tianfeng92** [comment]
Hi @anselmbradford,

I've followed the steps with the latest version of Cypress, but I'm still seeing the config file in CommonJS syntax. Could you please share your method for generating the config file? Thanks!

Here's what I did:
```plaintext
1. Created a new, empty folder.
2. Installed the latest version of Cypress.
3. Ran `npx cypress open`, which automatically generated the config files.
```

However, the config file I obtained is still in CommonJS format:

```javascript
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});
```

For reference, I'm using the following Cypress version:
```plaintext
Cypress package version: 13.6.2
Cypress binary version: 13.6.2
Electron version: 25.8.4
Bundled Node version: 18.15.0
```
